[package]
name = "automock_core"
version = "0.0.1"
edition = "2024"
rust-version = "1.88.0"
description = "Core of automock that handles mocking logic."
license = "MIT"
repository = "https://github.com/alordash/automock"
readme = "../README.md"

[dependencies]
typeid = { workspace = true }
indexmap = { workspace = true }
cfg-if = { workspace = true }

#[dev-dependencies]
#automock = { workspace = true }

[features]
debug_naming = []

[lints.clippy]
needless_return = "allow"
match_like_matches_macro = "allow"
