// Generated by ChatGPT
use automock::*;

#[mock]
trait SameNamesA {
    fn foo(&self, value: i32) -> i32;
}

#[mock]
trait SameNamesB {
    fn foo(&self, value: i32) -> i32;
}
trait SameNamesDifferentGenerics {
    fn foo<T>(&self, value: T) -> T;
}
#[allow(unused)]
use __automock_generated_SameNamesDifferentGenericsMock::SameNamesDifferentGenericsMock;
#[allow(clippy::all)]
#[allow(unused)]
#[allow(private_interfaces)]
#[allow(private_bounds)]
#[allow(unreachable_pub)]
#[allow(nonstandard_style)]
mod __automock_generated_SameNamesDifferentGenericsMock {
    use super::*;
    #[doc(hidden)]
    pub struct foo_Call<'__aml, T> {
        pub __rs_generics: ::core::marker::PhantomData<(&'__aml (), Box<T>, T)>,
        pub(super) value: T,
    }
    impl<'__aml, T> ::automock::for_generated::IGenericsInfoProvider for foo_Call<'__aml, T> {
        fn get_generic_parameter_infos(
            &self,
        ) -> Vec<::automock::for_generated::GenericParameterInfo> {
            vec![automock::for_generated::generic_type_info(
                "T",
                core::any::type_name::<T>(),
            )]
        }
        fn hash_generics_type_ids(&self, hasher: &mut dyn ::std::hash::Hasher) {
            ::core::hash::Hash::hash(&[automock::for_generated::tid::<T>()], hasher);
        }
        fn hash_const_values(&self, hasher: &mut dyn ::std::hash::Hasher) {}
    }
    impl<'__aml, T> ::automock::for_generated::ICall for foo_Call<'__aml, T> {
        fn get_arg_infos(&self) -> Vec<::automock::for_generated::ArgInfo> {
            use ::automock::for_generated::arg_printing::*;
            vec![::automock::for_generated::ArgInfo::new(
                "value",
                &self.value,
                (&::automock::for_generated::ArgPrinter(::automock::transmute_lifetime!(
                    &self.value,
                    &T
                )))
                    .debug_string(),
            )]
        }
        fn get_ptr_to_boxed_tuple_of_refs(&self) -> *mut () {
            Box::leak(Box::new((&self.value,))) as *mut _ as *mut ()
        }
    }
    #[doc(hidden)]
    struct foo_ArgsChecker<'__aml, T> {
        pub __rs_generics: ::core::marker::PhantomData<(&'__aml (), Box<T>, T)>,
        value: ::automock::for_generated::Arg<T>,
    }
    impl<'__aml, T> ::automock::for_generated::IGenericsInfoProvider for foo_ArgsChecker<'__aml, T> {
        fn get_generic_parameter_infos(
            &self,
        ) -> Vec<::automock::for_generated::GenericParameterInfo> {
            vec![automock::for_generated::generic_type_info(
                "T",
                core::any::type_name::<T>(),
            )]
        }
        fn hash_generics_type_ids(&self, hasher: &mut dyn ::std::hash::Hasher) {
            ::core::hash::Hash::hash(&[automock::for_generated::tid::<T>()], hasher);
        }
        fn hash_const_values(&self, hasher: &mut dyn ::std::hash::Hasher) {}
    }
    impl<'__aml, T> ::automock::for_generated::IArgsChecker for foo_ArgsChecker<'__aml, T> {
        fn check(
            &self,
            dyn_call: &::automock::for_generated::DynCall<'_>,
        ) -> Vec<::automock::for_generated::ArgCheckResult> {
            use ::automock::for_generated::arg_printing::*;
            let call: &foo_Call<'__aml, T> = dyn_call.downcast_to();
            vec![
                ::automock::transmute_lifetime!(&self.value, &::automock::for_generated::Arg::<T>)
                    .check(
                        "value",
                        ::automock::transmute_lifetime!(&call.value),
                        (&::automock::for_generated::ArgPrinter(::automock::transmute_lifetime!(
                            &call.value,
                            &T
                        )))
                            .debug_string(),
                    ),
            ]
        }
        fn fmt_args(&self) -> String {
            use ::automock::for_generated::arg_printing::*;
            format!(
                "{}",
                (&::automock::for_generated::ArgPrinter(::automock::transmute_lifetime!(
                    &&self.value,
                    &&::automock::for_generated::Arg::<T>
                )))
                    .debug_string()
            )
        }
    }
    pub struct SameNamesDifferentGenericsMock<'__aml> {
        pub __rs_generics: ::core::marker::PhantomData<(&'__aml (),)>,
        #[doc(hidden)]
        pub __mock_data: ::automock::for_generated::SharedMockData,
    }
    impl<'__aml> ::core::clone::Clone for SameNamesDifferentGenericsMock<'__aml> {
        #[inline]
        fn clone(&self) -> SameNamesDifferentGenericsMock<'__aml> {
            SameNamesDifferentGenericsMock::<'__aml> {
                __rs_generics: ::core::clone::Clone::clone(&self.__rs_generics),
                __mock_data: ::core::clone::Clone::clone(&self.__mock_data),
            }
        }
    }
    impl<'__aml> SameNamesDifferentGenerics for SameNamesDifferentGenericsMock<'__aml> {
        fn foo<T>(&self, value: T) -> T {
            let call = foo_Call::<'_, T> {
                __rs_generics: ::core::marker::PhantomData,
                value: ::automock::transmute_lifetime!(value),
            };
            let fn_data: &::automock::for_generated::FnData<
                '_,
                SameNamesDifferentGenericsMock<'_>,
                true,
                false,
                true,
            > = ::automock::for_generated::ISharedMockData::get_shared_fn_data(
                &self.__mock_data,
                "SameNamesDifferentGenerics",
                "foo",
                ::automock::for_generated::IGenericsInfoProvider::get_generics_hash_key(&call),
            );
            fn_data.handle(self, call)
        }
    }
    impl<'__aml> SameNamesDifferentGenericsMock<'__aml> {
        pub fn new() -> Self {
            Self {
                __rs_generics: ::core::marker::PhantomData,
                __mock_data: ::core::default::Default::default(),
            }
        }
        pub fn setup(&mut self) -> SameNamesDifferentGenericsSetup<'__aml> {
            SameNamesDifferentGenericsSetup::<'__aml> {
                __rs_generics: ::core::marker::PhantomData,
                __mock_data: self.__mock_data.clone(),
            }
        }
        pub fn received(&mut self) -> SameNamesDifferentGenericsReceived<'__aml> {
            SameNamesDifferentGenericsReceived::<'__aml> {
                __rs_generics: ::core::marker::PhantomData,
                __mock_data: self.__mock_data.clone(),
            }
        }
    }
    #[doc(hidden)]
    pub struct SameNamesDifferentGenericsSetup<'__aml> {
        pub __rs_generics: ::core::marker::PhantomData<(&'__aml (),)>,
        #[doc(hidden)]
        pub __mock_data: ::automock::for_generated::SharedMockData,
    }
    impl<'__aml> SameNamesDifferentGenericsSetup<'__aml> {
        pub fn foo<T>(
            &self,
            value: impl ::automock::for_generated::IntoArg<T>,
        ) -> ::automock::for_generated::FnConfigurator<
            '_,
            SameNamesDifferentGenericsMock<'__aml>,
            Self,
            (&'__aml mut T,),
            T,
            &SameNamesDifferentGenericsMock<'__aml>,
            true,
            false,
            true,
        > {
            let args_checker = foo_ArgsChecker::<'__aml, T> {
                __rs_generics: ::core::marker::PhantomData,
                value: ::automock::transmute_lifetime!(value.into_arg(|v| {
                    use ::automock::for_generated::arg_printing::*;
                    (&::automock::for_generated::ArgPrinter(v)).debug_string()
                })),
            };
            let fn_data: &::automock::for_generated::FnData<
                '_,
                SameNamesDifferentGenericsMock<'__aml>,
                true,
                false,
                true,
            > = ::automock::for_generated::ISharedMockData::get_shared_fn_data(
                &self.__mock_data,
                "SameNamesDifferentGenerics",
                "foo",
                ::automock::for_generated::IGenericsInfoProvider::get_generics_hash_key(
                    &args_checker,
                ),
            );
            let fn_configurator: ::automock::for_generated::FnConfigurator<
                '_,
                SameNamesDifferentGenericsMock<'__aml>,
                Self,
                (&'__aml mut T,),
                T,
                &SameNamesDifferentGenericsMock<'__aml>,
                true,
                false,
                true,
            > = fn_data.add_config(args_checker, self);
            ::automock::transmute_lifetime!(fn_configurator)
        }
    }
    #[doc(hidden)]
    pub struct SameNamesDifferentGenericsReceived<'__aml> {
        pub __rs_generics: ::core::marker::PhantomData<(&'__aml (),)>,
        #[doc(hidden)]
        pub __mock_data: ::automock::for_generated::SharedMockData,
    }
    impl<'__aml> ::core::clone::Clone for SameNamesDifferentGenericsReceived<'__aml> {
        #[inline]
        fn clone(&self) -> SameNamesDifferentGenericsReceived<'__aml> {
            SameNamesDifferentGenericsReceived::<'__aml> {
                __rs_generics: ::core::clone::Clone::clone(&self.__rs_generics),
                __mock_data: ::core::clone::Clone::clone(&self.__mock_data),
            }
        }
    }
    impl<'__aml> SameNamesDifferentGenericsReceived<'__aml> {
        pub fn foo<T>(
            &self,
            value: impl ::automock::for_generated::IntoArg<T>,
            times: ::automock::for_generated::Times,
        ) -> ::automock::for_generated::ArgRefsBinder<Self, (&'__aml mut T,)> {
            let args_checker = foo_ArgsChecker::<'__aml, T> {
                __rs_generics: ::core::marker::PhantomData,
                value: ::automock::transmute_lifetime!(value.into_arg(|v| {
                    use ::automock::for_generated::arg_printing::*;
                    (&::automock::for_generated::ArgPrinter(v)).debug_string()
                })),
            };
            let fn_data: &::automock::for_generated::FnData<
                '_,
                SameNamesDifferentGenericsMock<'_>,
                true,
                false,
                true,
            > = ::automock::for_generated::ISharedMockData::get_shared_fn_data(
                &self.__mock_data,
                "SameNamesDifferentGenerics",
                "foo",
                ::automock::for_generated::IGenericsInfoProvider::get_generics_hash_key(
                    &args_checker,
                ),
            );
            fn_data.verify_received(args_checker, times);
            automock::for_generated::ArgRefsBinder::new(self.clone())
        }
        pub fn no_other_calls(&self) {
            automock::for_generated::IMockData::verify_received_nothing_else(&self.__mock_data)
        }
    }
}

mod same_name_tests {
    use super::*;

    #[test]
    fn same_method_names_do_not_collide() {
        // Arrange
        let mut a = SameNamesAMock::new();
        let mut b = SameNamesBMock::new();
        let mut c = SameNamesDifferentGenericsMock::new();

        a.setup().foo(1).returns(10);
        b.setup().foo(1).returns(20);
        c.setup().foo(1).returns(30);

        // Act
        let a_result = a.foo(1);
        let b_result = b.foo(1);
        let c_result = c.foo(1);

        // Assert
        assert_eq!(a_result, 10);
        assert_eq!(b_result, 20);
        assert_eq!(c_result, 30);

        a.received().foo(1, Times::Once);
        b.received().foo(1, Times::Once);
        c.received().foo(1, Times::Once);
    }
}
